### ISSUE TITLE
Adding Dark mode

### ISSUE THREAD

**Issue by iamwatchdogs** [iamwatchdogs/LoanApprovalPredictionModel_Website#6]
## Introduction
I considered adding a dark mode to this front-end part, but we ran out of time. So, I had to wrap up my task with responsiveness.

## Idea (or) Approach
- Create and Place a button on the right-top corner.
- The button should be obvious and tell others that it's a dark mode button.
- Finally, add the functionality using JavaScript.

## Results
Before I merge it with the original Repo, You must demonstrate any of the following ways:
- *( **recommended** )* Host the static web page using GitHub Pages *( You can find it at: your forked repo -> settings -> Under Code and automation menu -> Pages )* and share your link with the chat.
- Record a small video and share it in the chat.

**Comment by Sisir2311** [comment]
Hey there, I am willing to contribute to this issue. I am confident in my ability to not only implement a dark theme but also ensure its compatibility with different browsers and devices, as well as maintaining a consistent and visually appealing design throughout the website. I pay great attention to detail and understand the importance of usability and accessibility considerations.

**Comment by Sisir2311** [comment]
Hey I have added the dark theme. Check the PR #8.

**Comment by iamwatchdogs** [comment]
I have verified and merged the PR. Thank you for your contribution.
